####
POST localhost:13000/accounts
Accept: application/json
Content-Type: application/json

{
  "name": "Yu Hong",
  "email": "gildong@emai7.net"
}

> {%
    client.global.set("id", response.body.id);
%}


####
GET localhost:13000/accounts
Accept: application/json
Content-Type: application/json


####
GET localhost:13000/accounts/{{id}}
Accept: application/json
Content-Type: application/json


####
PATCH localhost:13000/accounts/{{id}}
Accept: application/json
Content-Type: application/json

{
  "email": "123213@domain.com"
}


####
DELETE localhost:13000/accounts/{{id}}
Accept: application/json