####
POST localhost:13000/accounts/signup
Accept: application/json
Content-Type: application/json

{
  "name": "Yu Jae5",
  "email": "test5@email.com",
  "password": "password"
}

> {%
    client.global.set("id", response.body.id);
%}

####
POST localhost:13000/accounts/signin
Accept: application/json
Content-Type: application/json

{
  "email": "test5@email.com",
  "password": "password"
}

####
GET localhost:13000/accounts/findAll
Accept: application/json
Content-Type: application/json


####
GET localhost:13000/accounts/{{id}}
Accept: application/json
Content-Type: application/json


####
PATCH localhost:13000/accounts/{{id}}
Accept: application/json
Content-Type: application/json

{
  "email": "123213@domain.com"
}


####
DELETE localhost:13000/accounts/{{id}}
Accept: application/json